Repository CMU-313/fall22-hw3-team-duquesne, pull requests merged in 2022-10, with the labels that each got.

#1 added all new fields to document entity and deleted old, unused fields and added get and set functionality for each new field as well as getting and saving each inputted value into the database
  docs-core/src/main/java/com/sismics/docs/core/dao/DocumentDao.java
  docs-core/src/main/java/com/sismics/docs/core/dao/RelationDao.java
  docs-core/src/main/java/com/sismics/docs/core/dao/dto/DocumentDto.java
  docs-core/src/main/java/com/sismics/docs/core/model/jpa/Document.java
  docs-core/src/main/java/com/sismics/docs/core/util/indexing/LuceneIndexingHandler.java
  docs-web/src/main/java/com/sismics/docs/rest/resource/DocumentResource.java
Labels: backend

#2 Added new fields to document edit page and deleted irrelevant fields from the edit page
  docs-web/src/main/webapp/src/app/docs/app.js
  docs-web/src/main/webapp/src/locale/en.json
  docs-web/src/main/webapp/src/partial/docs/document.default.html
  docs-web/src/main/webapp/src/partial/docs/document.edit.html
  docs-web/src/main/webapp/src/partial/docs/document.html
Labels: frontend

#21 Added new fields & deleted old fields from the database + updated database version
  docs-core/src/main/resources/config.properties
  docs-core/src/main/resources/db/update/dbupdate-028-0.sql
Labels: middleware

#20 Updated relevant information in document view mode
  docs-web/src/main/webapp/src/locale/en.json
  docs-web/src/main/webapp/src/partial/docs/document.html
  docs-web/src/main/webapp/src/partial/docs/document.view.content.html
Labels: frontend

#26 Added Test Cases for Automated Testing of Document Changes
  docs-web/src/test/java/com/sismics/docs/rest/TestDocumentResource.java
Labels: backend

#29 Added bound checks and empty-entry checks in form of pop-up window with notice message
  docs-web/src/main/webapp/src/partial/docs/document.edit.html
Labels: frontend

#31 Reformatted metadata form to fit in an application system
  docs-android/app/src/main/java/com/sismics/docs/activity/DocumentViewActivity.java
  docs-core/src/main/java/com/sismics/docs/core/dao/DocumentDao.java
  docs-core/src/main/java/com/sismics/docs/core/dao/RelationDao.java
  docs-core/src/main/java/com/sismics/docs/core/dao/dto/DocumentDto.java
  docs-core/src/main/java/com/sismics/docs/core/model/jpa/Document.java
  docs-core/src/main/java/com/sismics/docs/core/service/InboxService.java
  docs-core/src/main/java/com/sismics/docs/core/util/PdfUtil.java
  docs-core/src/main/java/com/sismics/docs/core/util/indexing/LuceneIndexingHandler.java
  docs-core/src/main/resources/config.properties
  docs-core/src/main/resources/db/update/dbupdate-028-0.sql
  docs-core/src/test/java/com/sismics/docs/core/dao/jpa/TestJpa.java
  docs-core/src/test/java/com/sismics/docs/core/util/TestFileUtil.java
  docs-web/src/main/java/com/sismics/docs/rest/resource/DocumentResource.java
  docs-web/src/main/webapp/src/app/docs/app.js
  docs-web/src/main/webapp/src/locale/en.json
  docs-web/src/main/webapp/src/partial/docs/document.default.html
  docs-web/src/main/webapp/src/partial/docs/document.edit.html
  docs-web/src/main/webapp/src/partial/docs/document.html
  docs-web/src/main/webapp/src/partial/docs/document.view.content.html
  docs-web/src/test/java/com/sismics/docs/rest/TestAclResource.java
  docs-web/src/test/java/com/sismics/docs/rest/TestDocumentResource.java
  docs-web/src/test/java/com/sismics/docs/rest/TestRouteResource.java
  docs-web/src/test/java/com/sismics/docs/rest/TestTagResource.java
Labels: documentation, enhancement, backend, frontend, middleware, quality assurance
